services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: clareo_dev_2024
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: valkey/valkey:8
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://teste:clareo_dev_2024@postgres:5432/clareo_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
    environment:
      DATABASE_URL: postgres://teste:clareo_dev_2024@postgres:5432/clareo_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle

volumes:
  pg_data:
  bundle_cache:
